.PHONY: test debug deinstall

test:
	uv run cube test terminalbench-cube

debug:
	uv run python -m terminalbench_cube.debug

install:
	uv sync --all-extras
	uv pip install -e .
	uv run scripts/create_task_metadata.py
